BINARY_BAYES_OPT = "BinaryBayesOpt"
BINARY_BAYES_OPT_WARM_START = "BinaryBayesoptWarmStart"
SIMULATED_ANNEALING = "SimulatedAnnealing"
PARTICLE_SWARM = "ParticleSwarm"
BINARY_PARTICLE_SWARM = "BinaryParticleSwarm"
METRIC_MICRO="micro_F1"
METRIC_MACRO="macro_F1"
METRIC_WEIGHTED="weighted_F1"